### ISSUE TITLE
bug: https://jku.github.io/tuf-demo returns 404

### ISSUE THREAD

**Issue by rdimitrov** [jku/tuf-demo#76]
Hey, noticed that for some reason the https://jku.github.io/tuf-demo is not available.

<img width="676" alt="image" src="https://github.com/jku/tuf-demo/assets/16540482/7b748053-bc14-4f66-b76c-42d740736c40">

**Comment by rdimitrov** [comment]
my bad, I guess it's late enough :) I'm updating the examples on go-tuf-metadata and I for some reason I was expecting to find something like a folder structure when I click on the link. All is fine 👍

**Comment by jku** [comment]
I'd like to have something there myself :) 

If you have any easy-to-implement ideas, please file an issue on tuf-on-ci. Maybe just a semi-static html that has a link to timestamp.json  or something?
